### ISSUE TITLE
Dashes are explicitly removed from descriptions

### ISSUE THREAD

**Issue by ascott18** [duffn/dumb-password-rules#461]
This should say "9-30", but instead reads "930"

![image](https://user-images.githubusercontent.com/5017521/219792732-3d541d6b-f6d4-4de2-9d26-60c21c0a19c1.png)

https://github.com/duffn/dumb-password-rules/blob/9f58b1aa72c50b7218f4edd9bc032f49f8d635d3/src/pages/sites/thumbnails.njk#L22

**Comment by duffn** [comment]
Thanks for the issue. 

Ah, yeah. I was trying to make it so the clamped description under the thumbnail looked good without dashes and asterisks on the first line, but think it's probably fine to just use `site.description` and remove the `replace`s and just let it show like it is.

If you'd like to submit a PR, I'd review, otherwise I'll get to it later tonight.
